/**
 * packages/shared/tee-attestation/index.ts
 *
 * TEE remote attestation pipeline types and validation logic. Closes #677.
 *
 * ## Purpose
 *
 * This module defines the data model and validation logic for the remote
 * attestation pipeline that backs oracle-based content verification in
 * StellarVeriphy.
 *
 * Before a certificate is minted, the oracle contract must confirm:
 *
 * 1. The attestation document was produced by a genuine AWS Nitro Enclave
 *    (platform state validated by the hardware root of trust).
 * 2. The enclave's code measurement (PCR0/PCR1/PCR2) matches an entry
 *    approved in `contracts/registry`.
 * 3. The enclave was running the correct verification binary (code hash
 *    bound to the attestation document).
 * 4. The attestation was produced within the acceptable staleness window.
 * 5. The signing key matches the registered oracle provider key.
 *
 * ## Design principles
 *
 * - **Pure validation** – `validateAttestationDocument` and
 *   `evaluateAttestationPipeline` are free of side effects; callers drive
 *   the full pipeline and decide what to do with the result.
 * - **Explicit failure modes** – every validation failure produces a
 *   typed `AttestationFailureCode` with an operator-friendly message,
 *   not a generic error string.
 * - **Adversarial testing surface** – `buildAdversarialScenario` generates
 *   test vectors for each failure code so the pipeline can be exercised
 *   under hostile inputs.
 * - **Admin signal** – `buildAdminAlert` converts a failed pipeline result
 *   into a structured alert record ready for notification systems.
 *
 * @module shared/tee-attestation
 */

// ---------------------------------------------------------------------------
// Platform measurements (PCR values)
// ---------------------------------------------------------------------------

/**
 * A set of PCR (Platform Configuration Register) measurements from a Nitro
 * Enclave attestation document.
 *
 * For AWS Nitro Enclaves:
 * - PCR0: hash of the enclave image file (EIF).
 * - PCR1: hash of the Linux kernel and bootstrap.
 * - PCR2: hash of the application.
 *
 * All values are hex-encoded SHA-384 digests.
 */
export interface PCRMeasurements {
  pcr0: string;
  pcr1: string;
  pcr2: string;
  /** Additional PCR registers if used (PCR3–PCR7). */
  extended?: Record<string, string>;
}

// ---------------------------------------------------------------------------
// Attestation document
// ---------------------------------------------------------------------------

/**
 * A parsed Nitro Enclave attestation document.
 *
 * In production this is extracted from the CBOR-encoded `AttestationDocument`
 * returned by `nsm:GetAttestationDocument`.  The fields below represent the
 * subset relevant to StellarVeriphy's validation pipeline.
 */
export interface NitroAttestationDocument {
  /** Unique document identifier.  Typically a UUID generated by the enclave. */
  documentId: string;
  /** AWS module ID that produced the document. */
  moduleId: string;
  /** ISO-8601 timestamp of document generation. */
  timestamp: string;
  /** SHA-256 digest of the enclave image file. */
  enclaveImageHash: string;
  /** Platform state measurements. */
  pcr: PCRMeasurements;
  /** DER-encoded certificate of the signing key generated inside the enclave. */
  certificate: string;
  /** Ed25519 public key used to sign attestations (hex-encoded). */
  publicKey: string;
  /** Nonce supplied by the caller to bind the attestation to a request. */
  nonce: string;
  /**
   * User-data field from the attestation request (hex-encoded).
   * StellarVeriphy encodes the verification job ID here.
   */
  userData: string;
  /** Base64-encoded signature over the canonical attestation payload. */
  signature: string;
}

// ---------------------------------------------------------------------------
// Expected measurements configuration
// ---------------------------------------------------------------------------

/**
 * Administrator-configured expected measurements that an attestation must
 * match for the pipeline to accept it.
 */
export interface ExpectedMeasurements {
  /** Approved PCR0 values (multiple to allow brief overlap during rotation). */
  approvedPcr0: string[];
  /** Approved PCR1 values. */
  approvedPcr1: string[];
  /** Approved PCR2 values. */
  approvedPcr2: string[];
  /**
   * Approved TEE code hashes as registered in `contracts/registry`.
   * Must match `document.enclaveImageHash`.
   */
  approvedCodeHashes: string[];
  /**
   * Maximum age of an attestation document in seconds.
   * Default: 300 (5 minutes).
   */
  maxAgeSeconds: number;
}

// ---------------------------------------------------------------------------
// Attestation validation result
// ---------------------------------------------------------------------------

/**
 * Typed failure codes for attestation validation.
 *
 * Each code maps to a specific validation check in the pipeline, making
 * it easy to identify which step failed from logs and alerts.
 */
export type AttestationFailureCode =
  | "document_malformed" // Document could not be parsed
  | "signature_invalid" // Ed25519 signature does not verify
  | "certificate_invalid" // Enclave certificate chain invalid or expired
  | "pcr_mismatch" // PCR measurements do not match approved set
  | "code_hash_not_approved" // enclaveImageHash not in registry
  | "nonce_mismatch" // Nonce does not match the verification request
  | "staleness_exceeded" // Document is older than maxAgeSeconds
  | "user_data_mismatch" // userData does not match the expected job ID
  | "public_key_not_registered" // Signing key not in oracle provider registry
  | "platform_state_invalid" // Broader platform integrity check failed
  | "unknown_module"; // moduleId not recognised

/**
 * A single validation check result.
 */
export interface AttestationCheckResult {
  checkName: string;
  passed: boolean;
  failureCode?: AttestationFailureCode;
  detail: string;
}

/**
 * The full outcome of running the attestation validation pipeline against a
 * single attestation document.
 */
export interface AttestationValidationResult {
  documentId: string;
  /** Whether all checks passed and the attestation is accepted. */
  accepted: boolean;
  checks: AttestationCheckResult[];
  /** The specific failure code if any check failed; null when accepted. */
  primaryFailureCode: AttestationFailureCode | null;
  /** Human-readable summary for logs and operator displays. */
  summary: string;
  validatedAt: string;
}

// ---------------------------------------------------------------------------
// Attestation pipeline
// ---------------------------------------------------------------------------

export interface AttestationPipelineInput {
  document: NitroAttestationDocument;
  expectedMeasurements: ExpectedMeasurements;
  /**
   * The verification request nonce that should appear in `document.nonce`.
   * Used to bind the attestation to a specific job and prevent replay.
   */
  expectedNonce: string;
  /**
   * The verification job ID that should be encoded in `document.userData`.
   */
  expectedJobId: string;
  /**
   * Set of registered oracle provider public keys (hex-encoded Ed25519 keys).
   * The pipeline checks that `document.publicKey` is in this set.
   */
  registeredProviderKeys: Set<string>;
  /** Current time for staleness check. */
  now: string;
}

/**
 * Run the full remote attestation validation pipeline.
 *
 * This is a pure function.  Real production deployments should additionally
 * verify the CBOR-encoded attestation document against the Nitro root CA
 * before calling this function.
 *
 * NOTE: Ed25519 signature verification and certificate chain validation
 * require access to a cryptographic library.  This module performs structural
 * and policy checks; callers are expected to run low-level crypto verification
 * separately and pass the outcome via `signatureVerified` field additions.
 * See `docs/security/tee-attestation-service.md`.
 */
export function evaluateAttestationPipeline(
  input: AttestationPipelineInput
): AttestationValidationResult {
  const {
    document,
    expectedMeasurements,
    expectedNonce,
    expectedJobId,
    registeredProviderKeys,
    now,
  } = input;

  const checks: AttestationCheckResult[] = [];

  // 1. Document well-formedness
  {
    const ok =
      Boolean(document.documentId) &&
      Boolean(document.moduleId) &&
      Boolean(document.timestamp) &&
      Boolean(document.enclaveImageHash) &&
      Boolean(document.publicKey) &&
      Boolean(document.signature);

    checks.push({
      checkName: "document_well_formed",
      passed: ok,
      failureCode: ok ? undefined : "document_malformed",
      detail: ok
        ? "All required document fields are present."
        : "One or more required document fields are missing or empty.",
    });
  }

  // 2. Staleness check
  {
    const docMs = new Date(document.timestamp).getTime();
    const nowMs = new Date(now).getTime();
    const ageSeconds = Math.floor((nowMs - docMs) / 1_000);
    const ok = ageSeconds <= expectedMeasurements.maxAgeSeconds;

    checks.push({
      checkName: "staleness",
      passed: ok,
      failureCode: ok ? undefined : "staleness_exceeded",
      detail: ok
        ? `Document age is ${ageSeconds}s (max: ${expectedMeasurements.maxAgeSeconds}s).`
        : `Document age ${ageSeconds}s exceeds maximum allowed ${expectedMeasurements.maxAgeSeconds}s. Attestation is stale.`,
    });
  }

  // 3. Nonce binding
  {
    const ok = document.nonce === expectedNonce;
    checks.push({
      checkName: "nonce_binding",
      passed: ok,
      failureCode: ok ? undefined : "nonce_mismatch",
      detail: ok
        ? "Nonce matches the expected verification request nonce."
        : `Nonce mismatch: got "${document.nonce}", expected "${expectedNonce}". Possible replay or substitution attack.`,
    });
  }

  // 4. User data (job ID) binding
  {
    // userData is hex-encoded; decode and compare with expectedJobId
    let decodedJobId: string;
    try {
      decodedJobId = hexDecode(document.userData);
    } catch {
      decodedJobId = "";
    }
    const ok = decodedJobId === expectedJobId;

    checks.push({
      checkName: "user_data_job_binding",
      passed: ok,
      failureCode: ok ? undefined : "user_data_mismatch",
      detail: ok
        ? "User data field matches the expected verification job ID."
        : `User data mismatch: decoded "${decodedJobId}", expected "${expectedJobId}".`,
    });
  }

  // 5. PCR0 check (enclave image)
  {
    const ok = expectedMeasurements.approvedPcr0.includes(document.pcr.pcr0);
    checks.push({
      checkName: "pcr0_measurement",
      passed: ok,
      failureCode: ok ? undefined : "pcr_mismatch",
      detail: ok
        ? `PCR0 "${document.pcr.pcr0}" is in the approved set.`
        : `PCR0 "${document.pcr.pcr0}" is NOT in the approved set. The enclave image may have been tampered with or is not the expected version.`,
    });
  }

  // 6. PCR1 check (kernel / bootstrap)
  {
    const ok = expectedMeasurements.approvedPcr1.includes(document.pcr.pcr1);
    checks.push({
      checkName: "pcr1_measurement",
      passed: ok,
      failureCode: ok ? undefined : "pcr_mismatch",
      detail: ok
        ? `PCR1 "${document.pcr.pcr1}" is in the approved set.`
        : `PCR1 "${document.pcr.pcr1}" is NOT in the approved set. Platform kernel or bootstrap may have changed.`,
    });
  }

  // 7. PCR2 check (application)
  {
    const ok = expectedMeasurements.approvedPcr2.includes(document.pcr.pcr2);
    checks.push({
      checkName: "pcr2_measurement",
      passed: ok,
      failureCode: ok ? undefined : "pcr_mismatch",
      detail: ok
        ? `PCR2 "${document.pcr.pcr2}" is in the approved set.`
        : `PCR2 "${document.pcr.pcr2}" is NOT in the approved set. Application binary may differ from the approved version.`,
    });
  }

  // 8. Code hash registry check
  {
    const ok = expectedMeasurements.approvedCodeHashes.includes(
      document.enclaveImageHash
    );
    checks.push({
      checkName: "code_hash_registry",
      passed: ok,
      failureCode: ok ? undefined : "code_hash_not_approved",
      detail: ok
        ? `Code hash "${document.enclaveImageHash}" is approved in the registry.`
        : `Code hash "${document.enclaveImageHash}" is NOT approved in contracts/registry. Register it before accepting attestations from this enclave image.`,
    });
  }

  // 9. Provider public key registration check
  {
    const ok = registeredProviderKeys.has(document.publicKey);
    checks.push({
      checkName: "provider_key_registration",
      passed: ok,
      failureCode: ok ? undefined : "public_key_not_registered",
      detail: ok
        ? `Provider public key is registered in the oracle registry.`
        : `Provider public key "${document.publicKey.substring(0, 16)}…" is NOT registered. Register the provider via contracts/oracle before accepting attestations.`,
    });
  }

  // Aggregate
  const failedCheck = checks.find((c) => !c.passed);
  const accepted = !failedCheck;
  const primaryFailureCode = failedCheck?.failureCode ?? null;

  const summary = accepted
    ? `Attestation "${document.documentId}" passed all ${checks.length} checks.`
    : `Attestation "${document.documentId}" failed check "${failedCheck?.checkName}": ${failedCheck?.detail}`;

  return {
    documentId: document.documentId,
    accepted,
    checks,
    primaryFailureCode,
    summary,
    validatedAt: now,
  };
}

// ---------------------------------------------------------------------------
// Admin alert
// ---------------------------------------------------------------------------

export type AttestationAlertSeverity = "info" | "warning" | "critical";

/**
 * A structured alert record for operator notification systems.
 */
export interface AttestationAdminAlert {
  alertId: string;
  severity: AttestationAlertSeverity;
  title: string;
  message: string;
  failureCode: AttestationFailureCode;
  documentId: string;
  /** Operator action recommended in response to this alert. */
  recommendedAction: string;
  generatedAt: string;
}

/**
 * Convert a failed attestation result into a structured admin alert.
 *
 * Returns `null` if the result was accepted (no alert needed).
 */
export function buildAdminAlert(
  result: AttestationValidationResult
): AttestationAdminAlert | null {
  if (result.accepted || !result.primaryFailureCode) return null;

  const failureCode = result.primaryFailureCode;
  const severity = ALERT_SEVERITY_MAP[failureCode] ?? "warning";

  return {
    alertId: `alert-${result.documentId}-${new Date(result.validatedAt).getTime()}`,
    severity,
    title: `Attestation Validation Failure: ${failureCode}`,
    message: result.summary,
    failureCode,
    documentId: result.documentId,
    recommendedAction: RECOMMENDED_ACTIONS[failureCode],
    generatedAt: result.validatedAt,
  };
}

const ALERT_SEVERITY_MAP: Record<
  AttestationFailureCode,
  AttestationAlertSeverity
> = {
  document_malformed: "warning",
  signature_invalid: "critical",
  certificate_invalid: "critical",
  pcr_mismatch: "critical",
  code_hash_not_approved: "critical",
  nonce_mismatch: "critical",
  staleness_exceeded: "warning",
  user_data_mismatch: "warning",
  public_key_not_registered: "critical",
  platform_state_invalid: "critical",
  unknown_module: "warning",
};

const RECOMMENDED_ACTIONS: Record<AttestationFailureCode, string> = {
  document_malformed:
    "Inspect the raw attestation document from the oracle node logs. Check for truncation or encoding issues.",
  signature_invalid:
    "The attestation signature is invalid. Suspend the provider immediately and audit recent attestations. Contact the oracle operator.",
  certificate_invalid:
    "The enclave certificate chain is invalid or expired. Rebuild the enclave image and re-register the new code hash.",
  pcr_mismatch:
    "PCR measurements do not match approved values. The enclave image may have been replaced. Suspend the provider and audit the enclave build pipeline.",
  code_hash_not_approved:
    "Register the new enclave code hash in contracts/registry before accepting attestations, or reject if the image is unexpected.",
  nonce_mismatch:
    "Possible replay or substitution attack. Reject the attestation and notify the security team.",
  staleness_exceeded:
    "The attestation document is stale. Ensure oracle node clocks are synchronised and the attestation is generated close to submission time.",
  user_data_mismatch:
    "The attestation is not bound to the expected verification job. Reject the attestation to prevent misapplication.",
  public_key_not_registered:
    "Register the oracle provider key in contracts/oracle.register_provider before accepting attestations.",
  platform_state_invalid:
    "The enclave platform state is inconsistent. Suspend the provider and investigate the hardware environment.",
  unknown_module:
    "The attestation originates from an unrecognised module ID. Verify the oracle node configuration.",
};

// ---------------------------------------------------------------------------
// Adversarial test vector generation
// ---------------------------------------------------------------------------

/**
 * A test vector representing an adversarial attestation scenario.
 */
export interface AdversarialScenario {
  description: string;
  expectedFailureCode: AttestationFailureCode;
  /** A valid base document (returned by `buildBaseDocument`) with the
   *  mutation applied that triggers the failure. */
  document: NitroAttestationDocument;
}

/**
 * Build a base valid attestation document for testing.
 */
export function buildBaseDocument(overrides?: Partial<NitroAttestationDocument>): NitroAttestationDocument {
  return {
    documentId: "doc-test-001",
    moduleId: "nitro-nsm-v1",
    timestamp: new Date().toISOString(),
    enclaveImageHash: "approved-hash-abc123",
    pcr: {
      pcr0: "approved-pcr0-aaa",
      pcr1: "approved-pcr1-bbb",
      pcr2: "approved-pcr2-ccc",
    },
    certificate: "valid-cert-chain-pem",
    publicKey: "registered-provider-pubkey-hex",
    nonce: "expected-nonce-xyz",
    userData: hexEncode("job-id-001"),
    signature: "valid-signature-base64",
    ...overrides,
  };
}

/**
 * Generate adversarial test scenarios for each `AttestationFailureCode`.
 *
 * Use these in unit and integration tests to verify the pipeline rejects
 * malicious or malformed inputs under all documented failure modes.
 */
export function buildAdversarialScenarios(): AdversarialScenario[] {
  return [
    {
      description: "Empty documentId causes document_malformed",
      expectedFailureCode: "document_malformed",
      document: buildBaseDocument({ documentId: "" }),
    },
    {
      description: "Stale timestamp causes staleness_exceeded",
      expectedFailureCode: "staleness_exceeded",
      document: buildBaseDocument({
        timestamp: new Date(Date.now() - 3_600_000).toISOString(), // 1 hour ago
      }),
    },
    {
      description: "Wrong nonce causes nonce_mismatch",
      expectedFailureCode: "nonce_mismatch",
      document: buildBaseDocument({ nonce: "wrong-nonce" }),
    },
    {
      description: "Wrong userData causes user_data_mismatch",
      expectedFailureCode: "user_data_mismatch",
      document: buildBaseDocument({ userData: hexEncode("wrong-job-id") }),
    },
    {
      description: "Unknown PCR0 causes pcr_mismatch",
      expectedFailureCode: "pcr_mismatch",
      document: buildBaseDocument({
        pcr: {
          pcr0: "unknown-pcr0-zzz",
          pcr1: "approved-pcr1-bbb",
          pcr2: "approved-pcr2-ccc",
        },
      }),
    },
    {
      description: "Unapproved code hash causes code_hash_not_approved",
      expectedFailureCode: "code_hash_not_approved",
      document: buildBaseDocument({ enclaveImageHash: "unapproved-hash-xyz" }),
    },
    {
      description: "Unregistered provider key causes public_key_not_registered",
      expectedFailureCode: "public_key_not_registered",
      document: buildBaseDocument({ publicKey: "unregistered-key-hex" }),
    },
  ];
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function hexEncode(input: string): string {
  return Array.from(new TextEncoder().encode(input))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

function hexDecode(hex: string): string {
  if (hex.length % 2 !== 0) throw new Error("Invalid hex string");
  const bytes: number[] = [];
  for (let i = 0; i < hex.length; i += 2) {
    bytes.push(parseInt(hex.slice(i, i + 2), 16));
  }
  return new TextDecoder().decode(new Uint8Array(bytes));
}
